In [5]:
import numpy as np
import pandas as pd

In [6]:
data1=pd.read_csv('C:/Deloitte Folder/Building_Permits.csv')

C:\Users\gauravn\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (22,32) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [7]:
data1.head()

Permit Number  Permit Type            Permit Type Definition  \
0  201505065519            4                      sign - erect   
1  201604195146            4                      sign - erect   
2  201605278609            3  additions alterations or repairs   
3  201611072166            8            otc alterations permit   
4  201611283529            6                       demolitions   

  Permit Creation Date Block  Lot  Street Number Street Number Suffix  \
0           05/06/2015  0326  023            140                  NaN   
1           04/19/2016  0306  007            440                  NaN   
2           05/27/2016  0595  203           1647                  NaN   
3           11/07/2016  0156  011           1230                  NaN   
4           11/28/2016  0342  001            950                  NaN   

  Street Name Street Suffix  ...  Existing Construction Type  \
0       Ellis            St  ...                         3.0   
1       Geary            St  ...                         3.0   
2     Pacific            Av  ...                         1.0   
3     Pacific            Av  ...                         5.0   
4      Market            St  ...                         3.0   

  Existing Construction Type Description Proposed Construction Type  \
0                          constr type 3                        NaN   
1                          constr type 3                        NaN   
2                          constr type 1                        1.0   
3                         wood frame (5)                        5.0   
4                          constr type 3                        NaN   

  Proposed Construction Type Description Site Permit Supervisor District  \
0                                    NaN         NaN                 3.0   
1                                    NaN         NaN                 3.0   
2                          constr type 1         NaN                 3.0   
3                         wood frame (5)         NaN                 3.0   
4                                    NaN         NaN                 6.0   

  Neighborhoods - Analysis Boundaries  Zipcode  \
0                          Tenderloin  94102.0   
1                          Tenderloin  94102.0   
2                        Russian Hill  94109.0   
3                            Nob Hill  94109.0   
4                          Tenderloin  94102.0   

                                    Location      Record ID  
0  (37.785719256680785, -122.40852313194863)  1380611233945  
1   (37.78733980600732, -122.41063199757738)  1420164406718  
2    (37.7946573324287, -122.42232562979227)  1424856504716  
3   (37.79595867909168, -122.41557405519474)  1443574295566  
4   (37.78315261897309, -122.40950883997789)   144548169992  

[5 rows x 43 columns]

In [8]:
l=list(data.isna().sum().sort_values(ascending=False))
per=(sum(l)/data.size)*100
round(per,2)

'''
OR
total_missing = df.isna().sum().sort_values(ascending = False)
total_missing_sum= total_missing.sum()
total = df.size
per = round((total_missing_sum/total)*100,2)
per
'''

NameError: name 'data' is not defined

# Simple imputer

In [9]:
data=pd.read_csv('C:/Users/gauravn/Desktop/Data.csv')
data

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [10]:
x=data.iloc[:,:-1].values
y= data.iloc[:,-1].values

In [11]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan,strategy = 'mean')
'''imputer = imputer.fit(x[:,1:3])
x[:,1:3] = imputer.transform(x[:,1:3])'''
imp=imputer.fit_transform(x[:,1:3])
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

# Encoding independent variable (using columntransformer and onehotencoding)

   Using of only onehotencoding can be done by creating dummy variables 

In [41]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing  import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x = np.array(ct.fit_transform(x))
print(x)


[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 nan]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 nan 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [44]:
'''from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,0]=le.fit_transform(x[:,0])
x'''

#label encoder is not used for labels having more than 2 class of values

'from sklearn.preprocessing import LabelEncoder\nle=LabelEncoder()\nx[:,0]=le.fit_transform(x[:,0])\nx'

# Encoding using label encoder(Dependent Variable)

use label encoding only on target variable which has only 2 classes of data

In [42]:
le1=LabelEncoder()
y=le1.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

# Splitting dataset into train and test data

In [46]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state=1)
#random state controls the shuffling of dataset for test and train everytime the set is run.
#if random state = value then everytime the the program is run whoever runs the program gets the same splits everytime
print('x_train:',x_train)
print('x_test:',x_test)
print('y_train:',y_train)
print('y_test:',y_test)

x_train: [[0.0 0.0 1.0 nan 52000.0]
 [0.0 1.0 0.0 40.0 nan]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]
x_test: [[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
y_train: [0 1 0 0 1 1 0 1]
y_test: [0 1]


# Feature Scaling

Perform these Scaling only after splitting the dataset.

fit() calculates the 

In [48]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:,3:] = sc.fit_transform(x_train[:,3:])
x_test[:,3:] = sc.transform(x_test[:,3:])
print('x train:',x_train)
print('x test:',x_test)

x train: [[0.0 0.0 1.0 nan -1.0182239953527132]
 [0.0 1.0 0.0 -0.03891021128204815 nan]
 [1.0 0.0 0.0 0.5058327466666259 0.5834766714942514]
 [0.0 0.0 1.0 -0.31128169025638514 -0.2974586952715791]
 [0.0 0.0 1.0 -1.8093248246152385 -1.3385641287221062]
 [1.0 0.0 0.0 1.0505757046152997 1.1440719048906889]
 [0.0 1.0 0.0 1.3229471835896367 1.4644120382600818]
 [1.0 0.0 0.0 -0.7198389087178906 -0.5377137952986237]]
x test: [[0.0 1.0 0.0 -1.400767606153733 -0.8580539286680166]
 [1.0 0.0 0.0 -0.44746742974355364 0.18305150478251025]]


# Cross Tab  

Cross tab function performs the cross tabulation of two factors.it counts the frequency of the given 2 factors and returns the result.

margin = true indicates the name of the columns and rows returned

In [53]:
d = {
    'Name':['Alisa','Bobby','Cathrine','Alisa','Bobby','Cathrine',
            'Alisa','Bobby','Cathrine','Alisa','Bobby','Cathrine'],
    'Exam':['Semester 1','Semester 1','Semester 1','Semester 1','Semester 1','Semester 1',
            'Semester 2','Semester 2','Semester 2','Semester 2','Semester 2','Semester 2'],
    
    'Subject':['Mathematics','Mathematics','Mathematics','Science','Science','Science',
               'Mathematics','Mathematics','Mathematics','Science','Science','Science'],
   'Result':['Pass','Pass','Fail','Pass','Fail','Pass','Pass','Fail','Fail','Pass','Pass','Fail']}

df1 = pd.DataFrame(d,columns=['Name','Exam','Subject','Result'])
df1

Name        Exam      Subject Result
0      Alisa  Semester 1  Mathematics   Pass
1      Bobby  Semester 1  Mathematics   Pass
2   Cathrine  Semester 1  Mathematics   Fail
3      Alisa  Semester 1      Science   Pass
4      Bobby  Semester 1      Science   Fail
5   Cathrine  Semester 1      Science   Pass
6      Alisa  Semester 2  Mathematics   Pass
7      Bobby  Semester 2  Mathematics   Fail
8   Cathrine  Semester 2  Mathematics   Fail
9      Alisa  Semester 2      Science   Pass
10     Bobby  Semester 2      Science   Pass
11  Cathrine  Semester 2      Science   Fail

In [57]:
crosstab = pd.crosstab(df1.Subject,df1.Result,margins = True)

In [59]:
crosstab.columns=['Fail','Pass','Rowtotal']
crosstab.index=['Mathematics','Science','Columntotal']
crosstab

Fail  Pass  Rowtotal
Mathematics     3     3         6
Science         2     4         6
Columntotal     5     7        12

In [62]:
#Identifying the Propotion of each column.( divide each value with the total(12))
crosstab/crosstab.iloc[2,2]

Fail      Pass  Rowtotal
Mathematics  0.250000  0.250000       0.5
Science      0.166667  0.333333       0.5
Columntotal  0.416667  0.583333       1.0

# Outliers

## Detecting Outliers:


    1. Boxplot          2. IQR         3. Z-Score
    
## Handling Outliers:
    
    1.  Trimming/Removing the outliers        2. Replace with mean/median.mode       3. Quantum based flooring and capping

In [94]:
sample= [15, 101, 18, 7, 13, 16, 11, 21, 5, 15, 10, 9]
outliers = []

In [95]:
#detecting outliers using IQR
def detect_outliers_iqr(data):
    data = sorted(data)
    q1 = np.percentile(data, 25)
    q3 = np.percentile(data, 75)
    # print(q1, q3)
    IQR = q3-q1
    lwr_bound = q1-(1.5*IQR)
    upr_bound = q3+(1.5*IQR)
    # print(lwr_bound, upr_bound)
    for i in data: 
        if (i<lwr_bound or i>upr_bound):
            outliers.append(i)
    return outliers# Driver code
sample_outliers = detect_outliers_iqr(sample)
print("Outliers from IQR method: ", sample_outliers)

Outliers from IQR method:  [101]


In [88]:
#detecting outliers using z-score
outliers=[]
def detect_outliers_zscore(data):
    thres = 3
    mean = np.mean(data)
    std = np.std(data)
    # print(mean, std)
    for i in data:
        z_score = (i-mean)/std
        if (np.abs(z_score) > thres):
            outliers1.append(i)
    return outliers# Driver code
sample_outliers = detect_outliers_zscore(sample)
print("Outliers from Z-scores method: ", sample_outliers)



Outliers from Z-scores method:  [101]


            Handing Outliers

In [117]:
#removing/Trimming
for i in sample_outliers:
    a=np.delete(sample,np.where(sample == i))
print(a)

[ 15 101  18   7  13  16  11  21   5  15  10   9]


In [118]:
#quantum based flooring and capping. this means deleting the values by bringing those outliers into some percentiles
#if the sample values > percentile then the outlier value is placed into some percentile else remains the same
tenth_percentile = np.percentile(sample,10)
ninetieth_percentile = np.percentile(sample,90)
b=np.where(sample>ninetieth_percentile,ninetieth_percentile,sample)
print('New array:',b)

New array: [15.  20.7 18.   7.  13.  16.  11.  20.7  5.  15.  10.   9. ]


In [119]:
#replacing with median(14)
median=np.median(sample)
for i in sample_outliers:
    c=np.where(sample==i,median,sample)
print('sample:',sample)
print('new array:',c)

sample: [15, 101, 18, 7, 13, 16, 11, 21, 5, 15, 10, 9]
new array: [ 15. 101.  18.   7.  13.  16.  11.  21.   5.  15.  10.   9.]
